package com.guy.class23b_and_4;

public class DataManager {

    public static String[] COUNTRIES = new String[]{
            "China",
            "India",
            "United States",
            "Indonesia",
            "Pakistan",
            "Nigeria",
            "Brazil",
            "Bangladesh",
            "Russia",
            "Mexico",
            "Japan",
            "Philippines",
            "Ethiopia",
            "Egypt",
            "Vietnam",
            "DR Congo",
            "Iran",
            "Turkey",
            "Germany",
            "France",
            "United Kingdom",
            "Thailand",
            "Tanzania",
            "South Africa",
            "Italy",
            "Myanmar",
            "Colombia",
            "South Korea",
            "Spain",
            "Kenya",
            "Argentina",
            "Algeria",
            "Sudan",
            "Uganda",
            "Iraq",
            "Ukraine",
            "Canada",
            "Poland",
            "Morocco",
            "Uzbekistan",
            "Saudi Arabia",
            "Yemen",
            "Peru",
            "Angola",
            "Malaysia",
            "Afghanistan",
            "Mozambique",
            "Ghana",
            "Ivory Coast",
            "Nepal",
            "Venezuela",
            "Madagascar",
            "Australia",
            "North Korea",
            "Cameroon",
            "Niger",
            "Taiwan",
            "Mali",
            "Burkina Faso",
            "Sri Lanka",
            "Syria",
            "Malawi",
            "Chile",
            "Kazakhstan",
            "Zambia",
            "Romania",
            "Ecuador",
            "Netherlands",
            "Somalia",
            "Senegal",
            "Guatemala",
            "Chad",
            "Cambodia",
            "Zimbabwe",
            "South Sudan",
            "Rwanda",
            "Guinea",
            "Burundi",
            "Benin",
            "Bolivia",
            "Tunisia",
            "Belgium",
            "Haiti",
            "Jordan",
            "Cuba",
            "Dominican Republic",
            "Czech Republic",
            "Sweden",
            "Greece",
            "Portugal",
            "Azerbaijan",
            "Israel",
            "Hungary",
            "Honduras",
            "Tajikistan",
            "United Arab Emirates",
            "Belarus",
            "Papua New Guinea",
            "Austria",
            "Switzerland",
            "Sierra Leone",
            "Togo",
            "Paraguay",
            "Laos",
            "Hong Kong (China)",
            "Kyrgyzstan",
            "El Salvador",
            "Libya",
            "Serbia",
            "Nicaragua",
            "Bulgaria",
            "Turkmenistan",
            "Congo",
            "Denmark",
            "Central African Republic",
            "Finland",
            "Lebanon",
            "Norway",
            "Palestine",
            "Singapore",
            "Slovakia",
            "Costa Rica",
            "New Zealand",
            "Ireland",
            "Oman",
            "Kuwait",
            "Liberia",
            "Mauritania",
            "Panama",
            "Croatia",
            "Georgia",
            "Eritrea",
            "Uruguay",
            "Mongolia",
            "Bosnia and Herzegovina",
            "Puerto Rico (United States)",
            "Armenia",
            "Lithuania",
            "Qatar",
            "Albania",
            "Jamaica",
            "Gambia",
            "Moldova",
            "Namibia",
            "Botswana",
            "Lesotho",
            "Gabon",
            "Slovenia",
            "Latvia",
            "North Macedonia",
            "Kosovo",
            "Guinea-Bissau",
            "Equatorial Guinea",
            "Bahrain",
            "Trinidad and Tobago",
            "Estonia",
            "East Timor",
            "Mauritius",
            "Eswatini",
            "Djibouti",
            "Cyprus",
            "Fiji",
            "Bhutan",
            "Comoros",
            "Guyana",
            "Solomon Islands",
            "Macau (China)",
            "Luxembourg",
            "Montenegro",
            "Suriname",
            "Western Sahara",
            "Cape Verde",
            "Malta",
            "Belize",
            "Brunei",
            "Maldives",
            "Bahamas",
            "Iceland",
            "Northern Cyprus",
            "Transnistria",
            "Vanuatu",
            "Barbados",
            "French Polynesia (France)",
            "New Caledonia (France)",
            "Abkhazia",
            "São Tomé and Príncipe",
            "Samoa",
            "Saint Lucia",
            "Guam (United States)",
            "Curaçao (Netherlands)",
            "Artsakh",
            "Grenada",
            "Kiribati",
            "Saint Vincent and the Grenadines",
            "Jersey (British Crown Dependency)",
            "Aruba (Netherlands)",
            "Micronesia",
            "Antigua and Barbuda",
            "Seychelles",
            "Tonga",
            "U.S. Virgin Islands (United States)",
            "Isle of Man (British Crown Dependency)",
            "Andorra",
            "Dominica",
            "Cayman Islands (United Kingdom)",
            "Bermuda (United Kingdom)",
            "Guernsey (British Crown Dependency)",
            "Greenland (Denmark)",
            "Faroe Islands (Denmark)",
            "South Ossetia",
            "American Samoa (United States)",
            "Saint Kitts and Nevis",
            "Northern Mariana Islands (United States)",
            "Turks and Caicos Islands (United Kingdom)",
            "Sint Maarten (Netherlands)",
            "Liechtenstein",
            "Marshall Islands",
            "Monaco",
            "San Marino",
            "Gibraltar (United Kingdom)",
            "Saint Martin (France)",
            "British Virgin Islands (United Kingdom)",
            "Åland (Finland)",
            "Palau",
            "Anguilla (United Kingdom)",
            "Cook Islands",
            "Nauru",
            "Wallis and Futuna (France)",
            "Tuvalu",
            "Saint Barthélemy (France)",
            "Saint Pierre and Miquelon (France)",
            "Saint Helena, Ascension and Tristan da Cunha (United Kingdom)",
            "Montserrat (United Kingdom)",
            "Falkland Islands (United Kingdom)",
            "Norfolk Island (Australia)",
            "Christmas Island (Australia)",
            "Tokelau (New Zealand)",
            "Niue",
            "Vatican City",
            "Cocos (Keeling) Islands (Australia)",
            "Pitcairn Islands (United Kingdom)",
    };
}
